spring:
  datasource:
    url: localhost:3306/test
    username: root
    password: 20060704
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          key: chb20060704
          expire: 7 * 24
  main:
    allow-bean-definition-overriding: false
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    port: 465
    username: c19859572508@163.com
    password: VVfQH7VDsHign2pk
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.guistar.entity
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
logging:
  level:
    org.springframework.security: INFO
    com.baomidou.mybatisplus: INFO